source/account/urls.py
from django.urls import path

from account.views import RegisterView, UserDetailView, UserChangeView, UserChangePasswordView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('update/', UserChangeView.as_view(), name='update'),
    path('password/', UserChangePasswordView.as_view(), name='password_change'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import ProductIndexViews, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ProductReviewCreateView, ReviewUpdateView, ReviewDeleteView


app_name = 'webapp'

urlpatterns = [
    path('', ProductIndexViews.as_view(), name='product_index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/review/', ProductReviewCreateView.as_view(), name='product_review'),
    path('product/<int:pk>/review/update/', ReviewUpdateView.as_view(), name='product_review_update'),
    path('product/<int:pk>/review/delete/', ReviewDeleteView.as_view(), name='product_review_delete'),
    path('product/<int:pk>/review/delete/', ReviewDeleteView.as_view(), name='product_review_delete'),

]

source/account/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

CATEGORY_CHOICES = [('electronics', 'Электроника'), ('clothes', 'Одежда'), ('food', 'Еда')]
# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=30, verbose_name="Заголовок")
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES, verbose_name="Категория")
    description = models.TextField(max_length=3000, verbose_name="Описание", null=True, blank=True)
    avatar = models.ImageField(blank=True, null=True, upload_to='product_avatar', verbose_name="Аватар", default='product_avatar/default.jpg')

    def get_absolute_url(self):
        return reverse('webapp:product', kwargs={'pk': self.pk})
class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=1, related_name='reviews', verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='reviews', verbose_name='Продукт')
    description = models.TextField(max_length=3000, verbose_name="Описание")
    rating = models.PositiveIntegerField(verbose_name='Оценка', validators=[MinValueValidator(1), MaxValueValidator(5)])
    moderated = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")


    class Meta:
        permissions = [('can_moderated', 'Может moderated статус'), ]

source/account/views.py
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView


from account.form import MyUserCreationForm, UserChangeForm


class RegisterView(CreateView):
    model = get_user_model()
    form_class = MyUserCreationForm
    template_name = 'user_create.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        next_url = self.request.POST.get('next')
        if next_url:
            return next_url

        return reverse('webapp:product_index')


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        review = user.reviews.order_by('-created_at')
        context['reviews'] = review
        return context


class UserChangeView(UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('account:detail', kwargs={'pk': self.get_object().pk})

class UserChangePasswordView(PasswordChangeView):
    template_name = 'user_change_password.html'

    def get_success_url(self):
        return reverse('account:user_view', kwargs={'pk': self.request.user.pk})

source/webapp/views/product_views.py
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect, reverse
from webapp.models import Product, Review
from webapp.form import ProductForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin


class ProductIndexViews(ListView):
    template_name = 'product/index.html'
    context_object_name = 'products'
    model = Product
    # ordering = ('-created_at',)


class ProductView(DetailView):
    template_name = 'product/product_view.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        reviews = product.reviews.order_by('-created_at')
        context['reviews'] = reviews
        return context


class ProductCreateView(CreateView):
    template_name = 'product/product_create.html'
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('webapp:product_index')


class ProductUpdateView(UpdateView):
    template_name = 'product/product_update.html'
    model = Product
    form_class = ProductForm


class ProductDeleteView(DeleteView):
    template_name = 'product/product_delete.html'
    model = Product
    success_url = reverse_lazy('webapp:product_index')

source/webapp/views/review_views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse
from webapp.models import Product, Review
from webapp.form import ReviewForm
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin


class ReviewList(PermissionRequiredMixin, ListView):
    template_name = 'review/review_list.html'
    model = Review
    form_class = ReviewForm


class ProductReviewCreateView(LoginRequiredMixin, CreateView):
    template_name = 'review/review_create.html'
    model = Review
    form_class = ReviewForm

    def get_success_url(self):
        return reverse('webapp:product', kwargs={'pk': self.object.product.pk})

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        form.instance.product = product
        form.instance.author = self.request.user
        return super().form_valid(form)



class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'review/review_update.html'
    model = Review
    form_class = ReviewForm

    def get_success_url(self):
        return reverse('webapp:product', kwargs={'pk': self.object.product.pk})

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_review') or self.get_object().author == self.request.user


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:product', kwargs={'pk': self.object.product.pk})

    def has_permission(self):
        return self.request.user.has_perm('webapp.delete_review') or self.get_object().author == self.request.user

source/account/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Вход</h1>
    <form action="" method="post" class="w-50 mx-auto">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="row mb-3">
            <label for="username" class="col-sm-4 col-form-label">Имя пользователя: </label>
            <div class="col-sm-8">
                <input type="text" name="username" id="username" class="form-control">
            </div>
        </div>
        <div class="row mb-3">
            <label for="password" class="col-sm-4 col-form-label">Пароль: </label>
            <div class="col-sm-8">
                <input type="password" class="form-control" name="password" id="password">
            </div>
        </div>
        <div class="d-flex">
            <button type="submit" class="btn btn-outline-success mx-auto px-5">Войти</button>
        </div>

    </form>

{% endblock %}

source/account/templates/user_change.html
{% extends 'base.html' %}
{% block content %}
<h1>Change Profile</h1>
<form action = "" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='Change'%}
</form></br>
{% endblock %}

source/account/templates/user_change_password.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mx-4">Change your Password</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='change'%}
</form></br>
{% endblock %}

source/account/templates/user_create.html
{% extends 'base.html' %}
{% block content %}
<h1>Create Account</h1>
<form action = "" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='Create'%}
</form></br>
{% endblock %}

source/account/templates/user_detail.html
{% extends 'base.html' %}
{% block nav %}
    {% if user_obj.pk == request.user.pk %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account:update'  %}">Редактировать </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account:password_change' %}">Смена пароля</a>
    </li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>

    <div class="card mb-3">
        <div class="row g-0">
            {% if user_obj.profile.avatar %}
                <div class="col-md-4">
                    <img src="{{ user_obj.profile.avatar.url }}" class="img-fluid rounded-start w-75">
                </div>
            {% endif %}
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
                    <p class="card-text">Имя: {{ user_obj.first_name }}</p>
                    <p class="card-text">Почта: {{ user_obj.email }}</p>
                </div>
            </div>
        </div>
    </div>
<h1 style="text-align: center">{{ user_obj.get_full_name|default:user_obj.username }} Review <i class="bi bi-bookmark-check"></i></h1>
    <div class="row">
    {% for review in reviews %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body" style="font-weight: bold">
              <div class="d-flex">
                 <h2><a href="{% url 'account:detail' review.author.pk %}">Имя: {{ review.author }}</a></h2>
                 <div class="ms-auto">
                    <a href="{% url 'webapp:product_review_update' review.pk %}" class= "btn btn-primary "><i class="bi bi-pencil mx-2" style="font-size:25px"></i></a>
                    <a href="{% url 'webapp:product_review_delete' review.pk %}" class= "btn btn-primary "><i class="bi bi-trash" style="font-size:25px"></i></a>
                 </div>
             </div>
              <p>Описание: {{ review.description }}</p>
              <p>Оценка: {{ review.rating }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
{% endblock %}

source/webapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href=" https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css "> `
    <title>{% block title %}Blog{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'webapp:product_index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% block nav %}{% endblock %}

            </ul>

            {% if request.user.is_authenticated %}
                    <p class="ms-auto text-secondary d-inline-block my-0 py-auto" >Привет, <a href="{% url 'account:detail' request.user.pk %}">{{ request.user.username }}</a></p>
                    <a class="btn btn-dark ms-2" href="{% url 'account:logout' %}?next={{ request.get_full_path }}">Выйти</a>
            {% else %}
                    <a class="btn btn-dark ms-auto" href="{% url 'account:login' %}?next={% if request.GET.next  %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Войти</a>
                    <a class="btn btn-outline-secondary ms-2" href="{% url 'account:create' %}?next={% if request.GET.next  %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Регистрация</a>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container ">
{% block content %}
{% endblock %}
</div>

<!-- JavaScript Bundle with Popper -->
<script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js "
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>

source/webapp/templates/partial/form.html
{% if not fields_only %}
{% csrf_token %}
{% endif %}

{% for error in form.non_field_errors%}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{%for field in form%}
    <div class="form-check">
        <p><label for="{{ field.id_for_label }}">{{field.label}}</label></p>
        {% for error in field.errors%}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
        <p>{{ field }}</p>
    </div>
{% endfor %}

{% if not fields_only %}
<input  type="submit" value="{{ button_text }}" class="btn btn-success mx-4"/>
{% endif %}

source/webapp/templates/product/index.html
{% extends 'base.html' %}


{% block nav %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'webapp:product_create' %}">Create Product</a>
    </li>
{% endblock %}

{% block content %}
<h1 style="text-align: center">Project Tracker <i class="bi bi-bookmark-check"></i></h1>
    <div class="row">
    {% for product in products %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body" style="font-weight: bold">
             <h2><a href="{% url 'webapp:product' product.pk  %}" style="text-decoration: none">{{ product.name }} </a></h2>
            <p>{{ product.get_category_display }}</p>
              <a href=""></a>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/product/product_create.html
{% extends 'base.html' %}
{% block content %}
<h1>Create Product</h1>
<form action = "" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='Create'%}
</form></br>
{% endblock %}

source/webapp/templates/product/product_delete.html
{% extends "base.html" %}
{% block title %}Delete Product{% endblock %}


{% block content %}
    <form method="POST" action="" class="text-center" style="color: black">
        <h1>Are you sure want to delete product </h1>
        <h2>Summary: {{ product.name }}</h2>
        <p>Description: {{ product.description }}</p>
        {% csrf_token %}
        <input class="btn" style="border:solid 2px black" type="submit" value="Yes" >
        <a style="border:solid 2px black" href="{% url "webapp:product" product.pk %}" class="btn rounded text-decoration-none link-dark">No</a>
    </form>
{% endblock %}

source/webapp/templates/product/product_update.html
{% extends 'base.html' %}
{% block content %}
<h1>Change Product</h1>
<form action = "" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='Change'%}
</form></br>
{% endblock %}

source/webapp/templates/product/product_view.html
{% extends 'base.html' %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'webapp:product_review' product.pk %}">Add review</a>
    </li>
{% endblock %}
{% block content %}
    <h1>Product</h1>
    <div class="card mb-3">
        <div class="row g-0">
            {% if product.avatar %}
                <div class="col-md-3">
                    <img src="{{ product.avatar.url }}" class="img-fluid rounded-start w-75">
                </div>
            {% endif %}
            <div class="col-md-9">
                <div class="card-body">
                     <div class="d-flex">
                         <h1>Название: {{ product.name }}</h1>
                         <div class="ms-auto">
                         <a href="{% url 'webapp:product_update' product.pk %}" class= "btn btn-primary "><i class="bi bi-pencil mx-2" style="font-size:25px"></i></a>
                         <a href="{% url 'webapp:product_delete' product.pk %}" class= "btn btn-primary "><i class="bi bi-trash" style="font-size:25px"></i></a>
                         </div>
                     </div>
                    <p class="card-text">Категория: {{ product.get_category_display }}</p>
                    <p class="card-text">Описание: {{ product.description }}</p>
                </div>

            </div>
        </div>
    </div>
<h1 style="text-align: center">Project Tracker <i class="bi bi-bookmark-check"></i></h1>
    <div class="row">
    {% for review in reviews %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body" style="font-weight: bold">
              <div class="d-flex">
                 <h2>Имя: {{ review.author }}</h2>
                 <div class="ms-auto">
                    <a href="{% url 'webapp:product_review_update' review.pk %}" class= "btn btn-primary "><i class="bi bi-pencil mx-2" style="font-size:25px"></i></a>
                    <a href="{% url 'webapp:product_review_delete' review.pk %}" class= "btn btn-primary "><i class="bi bi-trash" style="font-size:25px"></i></a>
                 </div>
             </div>
              <p>Описание: {{ review.description }}</p>
              <p>Оценка: {{ review.rating }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
</div>
{% endblock %}

source/webapp/templates/review/review_create.html
{% extends 'base.html' %}
{% block content %}
<h1>Add Review</h1>
<form action = "" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='Add'%}
</form></br>
{% endblock %}

source/webapp/templates/review/review_update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Update Review</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}